### ISSUE TITLE
cuda 11.8 image

### ISSUE THREAD

**Issue by technillogue** [ameli/manylinux-cuda#1]
This is incredibly useful, but it would be great to have 11.8. I tried building it myself but couldn't find the 11.8 equivalent for https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda-repo-rhel7-11-7-local-11.7.0_515.43.04-1.x86_64.rpm

**Comment by ameli** [comment]
Thank you for your feedback and interest in this repository! I have now added CUDA version 11.8. Feel free to check out the updated image on [DockerHub](https://hub.docker.com/r/sameli/manylinux2014_x86_64_cuda_11.8) as well.

**Comment by technillogue** [comment]
Thank you so much!
