### ISSUE TITLE
Provide full CUDA images as options

### ISSUE THREAD

**Issue by weikengchen** [ameli/manylinux-cuda#3]
To start with, I am from EECS UC Berkeley as well. Go Bears.

I am using PyO3 to compile a Python module from Rust that uses CUDA. The Rust crate that invokes CUDA is `cust`, which would specifically ask for `libcuda.so`. It seems that the current minimal version does not have this file right there.

So, I forked this repo and made a one-line change.
```dockerfile
RUN yum -y install cuda-${VER}.${ARCH}
```
https://github.com/l2iterative/manylinux-cuda/blob/main/docker/manylinux2014_x86_64_cuda_12.3/Dockerfile#L33

This works for me. I did eventually create a separate Docker image on Docker Hub because my GitHub actions need to. It has been tested to be needed and useful.

Nevertheless, I wonder if you would include such a full version (the image would be larger, 4.83 GB) as one of the images you are offering. Compared with pytorch's one which does not work for me, the repo here seems to have more predictable behaviors and is simplistic, and would be go-to options.

**Comment by ameli** [comment]
That's a pleasant coincidence! I noticed we share the same workplace at the RISE lab, where I currently work.

I appreciate your input on the code suggestion. Initially, we included the full CUDA installation in the docker image, but we recently made the decision to remove it. The reason for this change was to streamline the image size and prevent potential issues on some CI runners. The full CUDA toolkit comes with various components, such as debuggers, profilers, demo suites, and sanitizer APIs, which may not be necessary for most users and significantly increase the image size.

However, if your specific requirement is ``libcuda.so``, it's included with NVIDIA drivers, which I've now added to the image. You can test it with:

	docker run sameli/manylinux2014_x86_64_cuda_12.3 ldconfig -p | grep libcuda.so

This should output:

	libcuda.so.1 (libc6,x86-64) => /lib64/libcuda.so.1
	libcuda.so (libc6,x86-64) => /lib64/libcuda.so

Please let me know if this solution works for you as an alternative to the full installation. If ``libcuda`` is still not found during your compilation, I'm more than happy to add ``/lib64`` to the library path in the image.

**Comment by weikengchen** [comment]
<= yes! it works. I will close this issue.
