### ISSUE TITLE
`manylinux_2_28`?

### ISSUE THREAD

**Issue by makslevental** [ameli/manylinux-cuda#4]
First of all, thank you very much for putting this together - I had some wheels break many months ago because I couldn't get CUDA installed correctly and these enabled me to resume building those wheels.

But a question/feature-request: would it be possible to move to `manylinux_2_28` instead of `manylinux2014`? The reason being that `manylinux2014` wheels set `_GLIBCXX_USE_CXX11_ABI=0` and thus libs in those wheels cannot linked against in projects that use the new ABI (if 13 years old can be called new...). In addition, CentOS 7 (and `manylinux2014` with it) are [EOL this year](https://peps.python.org/pep-0599/#rationale) so you're probably gonna be forced to bump soon anyway...

**Comment by makslevental** [comment]
FWIW this this is basically the only thing I had to do to make it work

```
# Maybe not necessary? Dunno  - not usually a centos/rhel user...
RUN yum install -y epel-release
RUN yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel8/x86_64/cuda-rhel8.repo
# Satisfy DKMS dependency
RUN dnf module install -y nvidia-driver:latest-dkms
RUN yum -y install cuda-compiler-${VER}.${ARCH} \
                   cuda-libraries-${VER}.${ARCH} \
                   cuda-libraries-devel-${VER}.${ARCH}
```

**Comment by ameli** [comment]
Thanks for your suggestion! You're right, moving to manylinux_2_28 is timely with manylinux2014 nearing EOL. I've updated the Docker images for both X86_64 and AARCH64 accordingly. Feel free to try it and let me know if you have any feedback.

**Comment by makslevental** [comment]
Reporting back: it worked smoothly (I was worried 12.3 wouldn't work for my use case but it did). FYI/BTW I'm using the image to build [these wheels](https://github.com/makslevental/mlir-wheels/actions/runs/7768658287/job/21186841465) which power [this example](https://colab.research.google.com/drive/101VH2jsbmdOdDopNR4UX71UbP_bB8NPU?usp=sharing). Thanks again.
