### ISSUE TITLE
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver

### ISSUE THREAD

**Issue by SaidAltury-ibm** [ameli/manylinux-cuda#5]
when I start a container "docker run -it sameli/manylinux2014_x86_64_cuda_12.3" and run nvida-smi command inside it fails with the following message, am I missing something here?

[root@24c96d985c30 /]# nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

I have also tried "docker run --gpus all sameli/manylinux2014_x86_64_cuda_12.3 nvidia-smi"
output:
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown.
ERRO[0000] error waiting for container:

**Comment by ameli** [comment]
Thanks for reporting. The issue has been fixed by removing the NVIDIA driver from the images. More details are documented in [Driver Conflict](https://github.com/ameli/manylinux-cuda?tab=readme#driver-conflict).
